--CREATE DATABASE TipTrackers;
--GO
--USE TipTrackers;
--GO
--CREATE TABLE DailyIncome(DateOfIncome DATETIME PRIMARY KEY,
--							HoursWorked nchar(20),
--							HourlyWage nchar(20),
--							HourlyIncome nchar(20),
--							TipAmount nchar(20),
--							TotalDailyIncome nchar(20));
